apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agri-mortgage-secret-sync
  namespace: agri-mortgage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: agri-mortgage-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: agri-mortgage/prod
        property: datasource-url
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: agri-mortgage/prod
        property: datasource-username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: agri-mortgage/prod
        property: datasource-password
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: agri-mortgage/prod
        property: mysql-root-password
    - secretKey: MYSQL_APP_PASSWORD
      remoteRef:
        key: agri-mortgage/prod
        property: mysql-app-password
    - secretKey: APP_SECURITY_JWT_SECRET
      remoteRef:
        key: agri-mortgage/prod
        property: jwt-secret
