apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agri-mortgage
resources:
  - observability-stack.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: agri-mortgage-prometheus-config
    files:
      - prometheus.yml
      - alert-rules.yml
  - name: agri-mortgage-alertmanager-config
    files:
      - alertmanager.yml
  - name: agri-mortgage-grafana-datasources
    files:
      - datasource.yml
  - name: agri-mortgage-grafana-dashboards-provider
    files:
      - dashboards.yml
  - name: agri-mortgage-grafana-dashboard
    files:
      - dashboard.json
